[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../../src/utils" }
anyhow = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true }
petgraph = "0.6"
